import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { motion as m } from "framer-motion"
import Image from 'next/image'
import heroImg from '../public/wordcloud3.png'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <m.main
        initial={{y:'100%'}}
        animate={{y:'0%'}}
        transition={{duration:0.75,ease:"easeOut"}}
        exit={{opacity:0}}
        className={styles.home__conteiner}
      >
        <div className={styles.home__imageConteiner}>
        <Image alt='brain logo with words' className={styles.home__image} src={heroImg} fill  />
        </div>
        
      </m.main>
    </>
  )
}
