import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { motion as m } from "framer-motion"
import Badge from '@/components/Badge'
import { faMicrophone } from '@fortawesome/free-solid-svg-icons'
import { faBookOpen } from '@fortawesome/free-solid-svg-icons'
import {faInstagram} from '@fortawesome/free-brands-svg-icons'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/bianIcon.png" />
      </Head>
      <m.main
        initial={{y:'100%'}}
        animate={{y:'0%'}}
        transition={{duration:0.75,ease:"easeOut"}}
        exit={{opacity:0}}
        className={styles.home__conteiner}
      >
        <div className={styles.home__sectionTop}>
          <div className={styles.home__sectionTop_A}>
          section bLeft
          </div>
          <div className={styles.home__sectionTop_B}>
          section bRigth
          </div>
        </div>
        <m.div
        initial={{y:'100%'}}
        animate={{y:'0%'}}
        transition={{delay:0.75,duration:0.75,ease:"easeOut"}}
        exit={{opacity:0}}
        className={styles.home__sectionBottom}>
          <Badge icon={faMicrophone} title={"Podcast"} description={"Podcast dedicado a la psycologia y viajes"} />
          <Badge icon={faInstagram} title={"Instagram"} description={"Contenido para todos los dias"}/>
          <Badge icon={faBookOpen} title={"Consultas"} description={"Contactarme online por consultas"}/>
        </m.div>
      </m.main>    
    </>
  )
}
/*
<div className={styles.home__sectionA}>
          <div className={styles.home__imageConteiner}>
          <Image alt='brain logo with words' className={styles.home__image} src={heroImg} fill  />
          </div>
        </div>
        <div className={styles.home__sectionB}>
          <h3 className={styles.home__phrase}>&quot;Cuando haces lo que mas temes, puedes hacer cualquier cosa&quot;</h3>
          <p className={styles.home__phrase_author}>Stephen Richards.</p>
        </div>





*/