import React from 'react'
import styles from '../styles/Podcast.module.css'
import { motion as m } from "framer-motion"
import Head from 'next/head'

const Podcast = () => {
  return (
    <>
      <Head>
          <title>Podcast</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.2"/>
          <link rel="icon" href="/bianIcon.png" />
        </Head>
      <m.div
      initial={{y:'100%'}}
      animate={{y:'0%'}}
      transition={{duration:0.75,ease:"easeOut"}}
      exit={{opacity:0}}
      className={styles.podcast__conteiner}>
          Podcast
      </m.div>
    </>
  )
}

export default Podcast